services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./logs:/var/log/beyblade
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=beyblade_user
      - DB_PASSWORD=Kill!em!All # Please use a stronger password in production
      - DB_NAME=beyblade_db
    restart: unless-stopped
    ports:
      - "5000:5000" # Expose the Flask port for local development (optional)

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 25525286 # Please use a stronger password in production
      MYSQL_USER: beyblade_user
      MYSQL_PASSWORD: Kill!em!All # Please use a stronger password in production
      MYSQL_DATABASE: beyblade_db
    volumes:
      - ./db_data:/var/lib/mysql # Bind mount for host access

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./static:/var/www/html
    depends_on:
      - web
    restart: unless-stopped

