services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-Sample_root_password}
      MYSQL_USER: ${DB_USER:-beyblade_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-Sample_DB_Password}
      MYSQL_DATABASE: ${DB_NAME:-beyblade_db}
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes: # Only ONE volumes section
      - ./db_init:/docker-entrypoint-initdb.d # Bind mount for init script
      - ./db_data:/var/lib/mysql # Bind mount for database data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
    depends_on:
      - db

  web:
    build: ./app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER:-beyblade_user}
      DB_PASSWORD: ${DB_PASSWORD:-Sample_DB_Password}
      DB_NAME: ${DB_NAME:-beyblade_db}
    volumes:
      - ./app:/app
      - ./app/static:/app/static
      - ./app/templates:/app/templates